[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache_foundry"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# Fuzz testing configuration
[fuzz]
runs = 256
max_test_rejects = 65536

# Invariant testing configuration
[invariant]
runs = 256
depth = 15
fail_on_revert = false

# Formatter configuration
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"

# RPC endpoints
[rpc_endpoints]
chiado = "${CHIADO_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"
