name: CI

on:
  push:
    branches: [main, 001-liquid-democracy-engine]
  pull_request:
    branches: [main]

jobs:
  contracts:
    name: Smart Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: |
          cd contracts
          pnpm install

      - name: Build contracts
        run: |
          cd contracts
          forge build

      - name: Run tests
        run: |
          cd contracts
          forge test -vvv

      - name: Run coverage
        run: |
          cd contracts
          forge coverage

  enclave-service:
    name: Enclave Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: |
          cd enclave-service
          pnpm install

      - name: Build
        run: |
          cd enclave-service
          pnpm build

      - name: Run tests
        run: |
          cd enclave-service
          pnpm test

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build
        run: |
          cd frontend
          pnpm build

      - name: Run tests
        run: |
          cd frontend
          pnpm test

      - name: Type check
        run: |
          cd frontend
          pnpm check

  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint
